Lua api for CA
H3MapGenTeam/h3mapgen pull request #55
Opened 2018-02-06 02:41 UTC by Fanderman

added a new lua_wrapper.cpp file with the code to process function to lua. Made a very small test file to show how data is supposed to be provided. Made a few small changes across the rest of CA files. the main.cpp file is rather obsolete now. 

The function in c++ must be first compiled into .dll or .so file to be used in this form in lua. 

If you have any suggestions or see an error, write me so I will be able to fix it.

2018-02-06 08:34 UTC, radekmie commented
I've tried to compile it, but it failed at the old CA build.

```
/tmp/cc4G2FKV.o:(.bss+0x0): multiple definition of `seed'
components/ca/cellular_terrain.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:14: components/ca/ca] Error 1
```

Either update the `Makefile` to build it (and clean in the `clean` target) or provide any compilation notes and I'll update it.

2018-02-06 08:37 UTC, radekmie commented on components/ca/lua_wrapper.cpp
> +    */
Stick to the [LuaDoc](https://keplerproject.github.io/luadoc/) guidelines. [Example from `homm3lua`](https://github.com/radekmie/homm3lua/blob/master/homm3lua/homm3lua.c#L60-L68).

2018-02-06 22:52 UTC, acatai commented on components/ca/lua_wrapper.cpp
> +    */
Ja z kolei mam 

```
g++ -std=c++11 -pedantic -Wall -Wextra -Wformat -Wfloat-equal -W -Wreturn-type -pedantic-errors -Wundef   -c -o components/ca/board.o components/ca/board.cpp
In file included from components/ca/board.cpp:4:0:
components/ca/board.hpp:6:19: fatal error: lua.hpp: No such file or directory
compilation terminated.
```

Co chyba wskazuje, że coś jest nie tak w make, a dokładniej to nie ma dodanych flag kompilacji z Lua: -I, -l -fPIC i co tam jeszcze było potrzebne...

2018-02-06 23:41 UTC, Fanderman commented
Jutro naprawię i wyślę wszystkie pliki.

2018-02-09 02:18 UTC, Fanderman commented
Dodałem makefile na linuxa, kompiluje się u mnie plik terrain.so normalnie. Problem w tym, że przy samym 'require' w lua wywala error wczytywania, konkretnie wywala się przy wywołaniu funkcji 'terrain' w kodzie c++, podejrzewam, że błąd jest związany z użyciem structów, ale nie mogę tego potwierdzić. Czy wie ktoś może, czy da się to naprawić bez zmieniania struktury całego istniejącego już wcześniej kodu?

2018-02-09 08:57 UTC, acatai requested changes
Właśnie do tego się używało `extern "C"`, wywołanie `nm terrain.so` pokazuje jakie funkcje mają dziwne przedrostki a jakie nie.

Niestety próba zrobienia `#include "cellular_terrain.hpp"` z extern C powoduje masę errorów `template with C linkage`.
@radekmie Twoja sugestia?

2018-02-09 08:57 UTC, acatai commented on components/ca/lua_wrapper.cpp
> +#include "cellular_terrain.h"
`#include "cellular_terrain.hpp"`

2018-02-09 08:57 UTC, acatai commented on components/ca/Makefile
> +	$(CXX) $(CXXFLAGS) $^ $(LDLIBS) -shared -o terrain.so
Dodać `-fPIC` (pisałem ostatnio)
Swoją drogą @radekmie make ma być osobny i potem podepniesz czy od razu powinien być w chainie? Bo teraz zwykły make się sypie.

2018-02-09 11:11 UTC, radekmie commented
* Nie powinno tam być osobnego `Makefile`, tylko dopisać do tego głównego (chociaż jak już tam będzie, to je złączę).
* Wszelkie flagi potrzebne do Lua można dostać z `pkg-config` - dlatego mówiłem, żeby korzystać z istniejących `Makefile` (w tym `homm3lua`).
* `extern C` vs templatki - nie wiem, dlatego wolę C.

2018-02-09 11:39 UTC, acatai commented
Ale wiesz co - zastanawiam się co jest nie tak, bo ja przeciez normalnie w innych projektach korzystałem z w pełni templatowanego cpp, nad którym pisałem wrapper i działało

2018-02-09 14:44 UTC, acatai commented
OK, przyznam, że coś jest strasznie dziwnego bo nie działa mi nawet tak minimalistyczny przykład:
[ca.zip](https://github.com/radekmie/h3mapgen/files/1711344/ca.zip)

Nie wiem co jest. Nie jest to związane z templatami ani takimi rzeczami. 
`extern "C"` nie robiło różnicy. Próbowałem bawić się opcjami kompilacji też nic.
Trzeba to przysiąść i rozgrzebać co jest nie tak. C funkcję widzi bo się kompiluje (?), zaś Lua ma error już na poziomie require - nawet nie wywołania funkcji...

2018-02-24 20:59 UTC, closed without merging